# Generated by Django 5.2 on 2026-08-22 19:23

import core.storages
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(db_index=True, help_text='Assignment title', max_length=255)),
                ('description', models.TextField(db_index=True, help_text='Detailed assignment description')),
                ('deadline', models.DateTimeField(help_text='Submission deadline')),
                ('max_score', models.PositiveIntegerField(db_index=True, default=100, help_text='Maximum possible score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'db_table': 'assignment',
                'ordering': ['-created_at'],
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'category',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('certificate_number', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique certificate UUID', unique=True)),
                ('image', models.ImageField(blank=True, help_text='Изображение сертификата (PNG)', null=True, storage=core.storages.PublicMediaStorage(), upload_to='certificates/images/')),
                ('qr_code', models.ImageField(blank=True, help_text='Verification QR code image', null=True, storage=core.storages.PublicMediaStorage(), upload_to='certificates/qrcodes/')),
                ('issue_date', models.DateTimeField(auto_now_add=True, help_text='Date of issue')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'db_table': 'certificate',
                'ordering': ['-issue_date'],
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('description', models.CharField(db_index=True, max_length=256)),
                ('level', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE'), ('ADVANCED', 'ADVANCED')], default='INTERMEDIATE', max_length=20)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=20)),
                ('image', models.ImageField(storage=core.storages.PublicMediaStorage(), upload_to='courses/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=20)),
                ('duration', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'course',
                'ordering': ['-created_at'],
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('video', models.FileField(storage=core.storages.PrivateVideoStorage(), upload_to='courses/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'webm'])])),
                ('pdf', models.FileField(storage=core.storages.PrivateDocumentStorage(), upload_to='courses/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('description', models.TextField(blank=True, db_index=True)),
                ('order', models.PositiveIntegerField(db_index=True)),
                ('duration', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'db_table': 'lesson',
                'ordering': ['-created_at'],
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('method', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum Bank'), ('card', 'Bank Card')], db_index=True, help_text='Payment gateway method', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Transaction status', max_length=20)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique certificate UUID', unique=True)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Successful payment timestamp', null=True)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'payment',
                'ordering': ['-payment_date'],
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('text', models.TextField(db_index=True, help_text='Question text')),
                ('marks', models.PositiveIntegerField(db_index=True, default=1, help_text='Marks for this question')),
                ('option1', models.CharField(help_text='First option', max_length=255)),
                ('option2', models.CharField(help_text='Second option', max_length=255)),
                ('option3', models.CharField(help_text='Third option', max_length=255)),
                ('option4', models.CharField(help_text='Fourth option', max_length=255)),
                ('correct_answer', models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], help_text='Select the correct option', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'db_table': 'question',
                'ordering': ['-created_at'],
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(db_index=True, help_text='Quiz name', max_length=255)),
                ('description', models.TextField(blank=True, db_index=True, help_text='Quiz description', null=True)),
                ('time_limit_mins', models.PositiveIntegerField(default=20, help_text='Time limit in minutes')),
                ('attempts_count', models.PositiveIntegerField(default=3, help_text='Allowed attempts count')),
                ('min_score', models.PositiveIntegerField(db_index=True)),
                ('max_score', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quiz',
                'db_table': 'quiz',
                'ordering': ['-created_at'],
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('score', models.PositiveIntegerField(db_index=True, default=0, help_text='Total scored marks')),
                ('is_passed', models.BooleanField(default=False, help_text='Passing status')),
                ('started_at', models.DateTimeField(help_text='Время начала прохождения теста')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Время фактического завершения теста', null=True)),
            ],
            options={
                'verbose_name': 'quizattempt',
                'verbose_name_plural': 'quizattempts',
                'db_table': 'quizattempt',
                'ordering': ['-completed_at'],
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(help_text='Uploaded submission file', storage=core.storages.PrivateDocumentStorage(), upload_to='assignments/submissions/')),
                ('student_comment', models.TextField(blank=True, db_index=True, help_text='Comment from student', null=True)),
                ('score', models.PositiveIntegerField(blank=True, db_index=True, help_text='Score given by teacher', null=True)),
                ('teacher_comment', models.TextField(blank=True, db_index=True, help_text='Feedback from teacher', null=True)),
                ('is_graded', models.BooleanField(default=False, help_text='Grading status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(help_text='Target assignment', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='edumasterapp.assignment')),
            ],
            options={
                'verbose_name': 'assignmentsubmission',
                'verbose_name_plural': 'assignmentsubmissions',
                'db_table': 'assignmentsubmission',
                'ordering': ['-created_at'],
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
    ]
