# Generated by Django 5.2 on 2026-08-22 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edumasterapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(help_text='Student who submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(help_text='Certificate owner', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edumasterapp.category'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(help_text='Completed course', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='edumasterapp.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='edumasterapp.course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(help_text='Related lesson', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='edumasterapp.lesson'),
        ),
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(help_text='Target course', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='edumasterapp.course'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(help_text='Student making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(help_text='Related course', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='edumasterapp.course'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(help_text='Parent quiz', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='edumasterapp.quiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(help_text='Target quiz', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='edumasterapp.quiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(help_text='Student taking the quiz', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order')},
        ),
    ]
